### ISSUE TITLE
Build fails at several points

### ISSUE THREAD

**Issue by kisik21** [ohwgiles/laminar#1]
Tried to compile on Gentoo on my Raspberry Pi. Got this instead:
```
/home/kisik21/laminar/src/laminar.cpp: In member function ‘void Laminar::runFinished(Run*)’:
/home/kisik21/laminar/src/laminar.cpp:689:48: error: invalid conversion from ‘size_t* {aka unsigned int*}’ to ‘uLongf* {aka long unsigned int*}’ [-fpermissive]
             (unsigned char*)&r->log[0], logsize) == Z_OK) {
                                                ^
```
additionally, I had to install rapidjson for build to process, it happens to be included somewhere.

**Comment by ohwgiles** [comment]
rapidjson is definitely necessary. I've updated the documentation to reflect that.

I've also pushed a commit to fix the build error (affected all 32-bit platforms).

By the way, since you're building from source, note that the default configuration (laminard listens on `unix-abstract:laminar`) isn't yet supported in capnproto's current release, so you'll need to build that from its master branch or change `LAMINAR_BIND_RPC`)
