### ISSUE TITLE
Build Now button

### ISSUE THREAD

**Issue by cweagans** [ohwgiles/laminar#109]
(I know, I know, but hear me out)

I very much disagree with the notion of having a "Build now" button for e.g. deploying to production. In that case, your reasoning that it allows for doing a dumb thing is very solid.

However, we have (IMO) a legitimate need for something like this. We're a web agency, and in Jenkins right now, we have a "create new site" job. This isn't tied to any particular action in a git repository, but instead, to a client signing a physical contract. Because this job can exist, any member of the team can go in and spin up a new git repo, hosting account, etc. for this new client and it doesn't land on my plate.

It's not CI per se, but it seems like having compartmentalized jobs that can be triggered through a web UI with known inputs is a much better solution than just handing out SSH access to prod so that other members of the team can go fiddle with nginx config or whatever.

Out of curiosity, if a build now button is still a nonstarter, how would you recommend handling that kind of thing?

**Comment by ohwgiles** [comment]
Implementing a build now button also comes with a swathe of new difficulties. You suddenly need access controls to the frontend, or otherwise a way to specify which jobs or job parameters are safe to expose this way. Currently parameters are unstructured key=value pairs, the interdependencies between which are completely free-form according to your run script logic; Laminar frontend has no way of knowing which fields to render for providing parameters.

Furthermore, the road to "build now"-abuse is paved with legitimate needs, as I'm sure you can appreciate.

Laminar focuses on its niche as a lightweight CI/CD server. As you note, your use case is not actually CI at all. It sounds like what you want is a control panel UI which will invoke laminarc queue, so that you can track and log executions of such administrative tasks in the same environment as regular Laminar CI/CD. Is that fair? If so, it's not something that core Laminar will support, but there are a few ways to achieve more or less what you want.

The simplest is probably just mandating the command line and executing laminarc remotely directly:

```
ssh ci_server laminarc queue new-site customer=Acme
```

This way you can control access using ssh authorized keys. If access controls aren't important, you can also use remote instances of laminarc and expose the port on which laminard listens for RPC connections to the network, as described in the user manual.

If you actually need something clickable, you might try something quick and dirty like this:

```
#!/bin/bash
if [ "$REQUEST_METHOD" == "GET" ]; then
	cat <<-EOF
	Status: 200 OK
	Content-type: text/html

	<html>
	 <body>
	  <form method=post>
	   <label>Customer name</label><input name=customer><br>
	   <input type=submit>
	  </form>
	 </body>
	</html>
	EOF
elif [ "$REQUEST_METHOD" == "POST" ]; then
	declare -A PARAMS
	IFS=\& read -ra kvpairs
	for kv in ${kvpairs[@]}; do
		PARAMS[${kv%%=*}]="${kv##*=}"
	done
	# (will hopefully not need that sed in a later release)
	url=my.laminar.instance.example.com/jobs/$(laminarc start new-site customer=${PARAMS[customer]} | sed -E 's/\x1b(\[.|\\)//g' | tr : /)
	cat <<-EOF
	Status: 302 Found
	Location: $url

	EOF
else
	echo "Status: 500 Error"
fi
```

as a simple CGI script behind your reverse proxy.

**Comment by cweagans** [comment]
Thank you so much for the thorough answer! That's really helpful. I think I'll probably end up deploying Laminar as-is and then building a separate control panel for administrative actions.
