### ISSUE TITLE
Feature: Add ability to trigger builds from the web interface

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#11]
I don't know if this will pass your KISS principle, but would it be possible to start a job from the command interface?

Thanks

**Comment by ohwgiles** [comment]
Your comment says "command interface" but the title says "web interface" - I assume you mean the latter.

I actually very intentionally did not include this when designing laminar. It's more than just KISS. The button represents a _manual trigger_ action. In my opinion, there is no place for a manual trigger in the ideal continuous integration environment. Want to make a release? Push a git tag and implement a [post-receive hook](https://git-scm.com/docs/githooks#post-receive). Want to re-run a build due to sporadic failure/flaky tests? Fix the tests locally and push a patch. In my experience with other continuous integration platforms, the manual trigger button ends up being used in both of these cases (and others) as a crutch to avoid doing the correct thing, and the result is a negative impact on both traceability and quality. So I left it out so that laminar will encourage its administrators to build solid, reliable pipelines.

The other, less important reason is that in general this option would require the ability in the web client to trigger actions on the server. This would then mean instances could not be publicly accessible without a whole layer of access controls, user roles etc. Keeping the web interface read-only is an important design goal for laminar.

**Comment by palica** [comment]
OK, cool with me. I understand.
