### ISSUE TITLE
Do you want to start a list of Laminar-adjacent projects?

### ISSUE THREAD

**Issue by cweagans** [ohwgiles/laminar#116]
I just released https://github.com/cweagans/laminar-webform and https://github.com/cweagans/semantic-laminar-theme.

You mentioned https://github.com/adnanh/webhook in the docs.

Are there other relevant projects that might be worth listing out in their own section with some info about why they're useful in the context of Laminar?

**Comment by ohwgiles** [comment]
I think it would be pretty difficult to curate such a list. The aim with laminar is that *everything* could be integrated in just a few lines of shell or other language, so I don't want to be prescriptive. I should probably use more vague language around `webhook`, the only reason I link it explicitly is because it's not as well known as other tools I reference such as `ssh`, `git` and `docker`.

What I *am* interested in doing before the next release is starting to build a bunch of "examples" - for example helper scripts to trigger notifications, to prettify test runner output, example config files for configuring the reverse proxy, etc. This sort of fills the niche you're talking about.

**Comment by cweagans** [comment]
Not sure where this belongs, but it seems that webhook doesn't support laminar arguments very well. I opened https://github.com/adnanh/webhook/issues/406 to (hopefully) address it.
