### ISSUE TITLE
Suggestion: Grouped jobs

### ISSUE THREAD

**Issue by sbrl** [ohwgiles/laminar#124]
Now that I've been using Laminar CI for a while, I'm starting to accumulate a number of different run files for various different things. For these, most of them also have a context. To this end, it would be really nice if I could group them into a subfolder, like this:

```
jobs
 + config-check.run
 + config-check.conf
 + config-update.run
 + config-update.conf
 + apt/
     + config.conf
     + apt-nomad.run
     + apt-consul.run
     + ....
```

Like this, I would be able to group runs logically and have 1 config file for all of them in a subdirectory, instead of 1 config file each.

**Comment by ohwgiles** [comment]
I understand why this would be useful, but I wonder if there's a way this can be achieved without breaking the flat hierarchy. Although this seems like a fairly trivial change, I would really prefer not to complicate the core laminar offering and not even expose the potential for ambiguities in configuration (why should `config.conf` be treated specially? What if you have a job called `config.run`?).

The following describes a way to implement something similar to your layout. With a job layout like this, where e.g. `foo.conf` is common to `foo-check.run` and `foo-update.run`:

```
before
jobs
 + foo.conf
 + foo-check.run
 + foo-update.run
 + apt.conf
 + apt-nomad.run
 + apt-consul.run
```

You could create a [global before script](https://laminar.ohwg.net/docs.html#Script-execution-order) which had content like this:

```
#!/bin/bash
# Get the shared configuration file by stripping everything after the dash from the job name
CONF=$LAMINAR_HOME/cfg/jobs/${JOB%%-*}.conf
# Apply each environment variable declared in that file
while read -r line; do laminarc set $line; done < $CONF
```

**Comment by sbrl** [comment]
Oh wow, that's such a neat solution! I didn't even realise that was possible. That absolutely helps with my issue. I'll give that a try.

**Comment by ohwgiles** [comment]
Just realized I might have misread your question. What I suggested would be a solution for `$JOB.env` rather than `$JOB.conf` as you asked. The global `before` script runs after a context has already been assigned, so it cannot change `CONTEXTS` (or for that matter, influence `DESCRIPTION`). Depending on what you are actually using the context for, this might be enough, but if you need the context in order to control the executors, this is probably not enough.

**Comment by sbrl** [comment]
Ah, I see - I tmust have misunderstood your answer. Yeah, I want to control the executors to limit the number of jobs that run in parallel. This is really important to avoid my Raspberry Pi 3B+ from crashing..... :P

**Comment by ohwgiles** [comment]
I don't think I have a good solution to this problem at the moment. In general I prefer that Laminar offers one way to do something, but that this allows you as much flexibility as possible.

I agree there's room for improvement here though, going to think about it some more. Let me know if you have any other ideas for how this might be improved.

**Comment by sbrl** [comment]
Ah, ok. Hrm, I don't have any good suggestions at the moment either.

That reminds me, I need to revert that commit to my laminar config files that switches to a single config file per group.

**Comment by ohwgiles** [comment]
Currently, a job is assigned to a context by adding `CONTEXTS=context-name-globexpr` into `jobname.conf`. What if this were inverted, and contexts (which anyway have a conf file in order to exist) could specify `JOBS=job-name-globexpr`? If you are not using the `jobname.conf` file for anything other than setting the context, this would drastically reduce the number of files needed for your setup.

**Comment by sbrl** [comment]
That would work really nicely actually, yeah!

Indeed, I'm not setting anything at all other than the context. Any other details are either computed at runtime, or passed from the git server where the repository is located.

**Comment by sbrl** [comment]
:heart:
