### ISSUE TITLE
[discuss] Many similar jobs

### ISSUE THREAD

**Issue by jbglaw** [ohwgiles/laminar#147]
Hi!

I'd like to diskuss best practices (finally to be put into the docs.) I'm currently setting up a host to test Binutils/GDB/GAS/GCC. Basically it's four different jobs (building the four components), with only a different target (ie. vax-linux, aarch64-elf, ...)

I could just place four jobs and schedule those with a parameter (ie. target=vax-linux), but in the web frontend, I'd just see a hugh number of "binutils" jobs, some failing, some succeeding, without a way to group them by their supplied parameters. My current approach is that I put those four "master" jobs in a separate directory, and symlinked them a hundred times into the `cfg/jobs` directory with a name encoding the target (ie. `./cfg/jobs/binutils-vax-linux.run`). That way the runs show up in a useful way and can even be tab-grouped at the `/jobs` page.

Is this a recommended way? Or are there other means of making supplied parameters visible to the frontend?

Thanks a lot (esp. for the patch for "lots of log output"!)
  Jan-Benedict

**Comment by vvrein** [comment]
Yes, your current way is most simple and straightforward. 

For other possible way, take a look at https://github.com/ohwgiles/laminar/pull/144:
You can display `LAMINAR_REASON` variable with small fixes in index.html near this [line](https://github.com/ohwgiles/laminar/blob/master/src/resources/index.html#L38)
```
    <tr v-for="job in jobsRecent">
     <td>
      <span v-html="runIcon(job.result)"></span>
      <router-link :to="'/jobs/'+job.name">{{job.name}}</router-link>
      <router-link :to="'/jobs/'+job.name+'/'+job.number" v-if=job.reason>#{{job.number}} @{{job.reason}}</router-link>
      <router-link :to="'/jobs/'+job.name+'/'+job.number" v-else>#{{job.number}}</router-link>
      <br>
      <small>Took {{formatDuration(job.started, job.completed)}} at {{formatDate(job.started)}}</small>
     </td>
    </tr>
```

**Comment by ohwgiles** [comment]
@jbglaw yes generally I would recommend the symlink approach you use.

If you want to get fancier, you can then omit the parameter by doing a little match on the job name. So instead of doing `laminarc start binutils-vax-linux.run target=vax-linux` you can just put `target=${JOB#*-}` or similar at the top of your master script.

If you have a really dynamic setup, you can use a bootstrap job that takes the package and platform as parameters and creates the symlink on the fly before calling `laminarc queue` on it. Adds a little pollution to the frontend, so to that end I'm thinking about making jobs that begin with `.` invisible to the frontend, but that's another topic. Anyway, probably for your use case it's better to use the explicit symlinks, then you have a simple and clear way of defining the valid combinations. You would have to do that somehow anyway.

Also, if you want, you can store your "master" jobs in the `cfg/jobs/` directory, as long as they don't end in `.run` they will be ignored by laminar.

**Comment by jbglaw** [comment]
@ohwgiles With symlinks and parsing the job name, that's exactly how I built it. (I haven't even supplied a variable for the target, as this was the obvious solution.)

However, adding a bootstrap job that creates the symlinks and schedules jobs is a good idea, I just did that.

**Comment by jbglaw** [comment]
I think I'm happy, so let's close this.

**Comment by matrss** [comment]
I know this issue is older, but since I have a very similar use case I'll ask here: if I dynamically create a symlink to run as a job, is it safe to delete the symlink immediately after `laminarc queue`ing it? I am currently cleaning up the symlink in a EXIT trap in my job script, but since `laminarc queue` does not block this removal could happen while the triggered job is still in the queue. So far it looks like this is safe to do, but I just want to make sure.

**Comment by ohwgiles** [comment]
@matrss I don't think that is safe. Laminar does not resolve the symbolic link at queue time or at all, it executes it directly at run time.

Suggest you stick with `EXIT` trap in job script, or alternatively use an `.after` script

**Comment by matrss** [comment]
Ah okay, that's what I thought might be a problem. To clarify, what I meant with the EXIT trap is that I have a job A which creates a symlink B for another job and then `laminarc queue`'s B. Then, in the EXIT trap of the job script of A I currently cleanup that symlink. Since that can run while B is still in the queue this is unsafe, right?

I'll try to move the cleanup part to the "triggered" job or a .after script.

**Comment by ohwgiles** [comment]
> Since that can run while B is still in the queue this is unsafe, right?

Right

> I'll try to move the cleanup part to the "triggered" job or a .after script.

:+1:
