### ISSUE TITLE
Configuration reload before job run

### ISSUE THREAD

**Issue by Valicek1** [ohwgiles/laminar#34]
Hi, 
it would be nice if job/node (at least job) config was parsed before job run (trigger event) - in more complex scenarios with nodes, there is problem with jobs queued forever. 
Example: Create job `hello2.run` and it's config `hello2.conf`, then execute `laminarc trigger hello2` - job si queued forever. (no `hello2.conf` parsed until daemon restart). 

By studying sources, I didn't found any simple workaround - should I create patch/pullrequest? I'd appraise you to handle this simple fix by yourself - I won't like to mess your clean code by my hand :-D

**Comment by ohwgiles** [comment]
Yes I’ve been wondering when someone would mention this. It’s marked as TODO in `Laminar::Laminar()`. Unfortunately it’s not so trivial to do this properly. The configuration is also used to organise jobs on the UI, so every request for that page would have to re-parse the config files. This is super inefficient which is why I currently do it once at startup. I think the only right way to do it is to set up a callback with `inotify` so that laminar will know when to reread the configuration files.

Generally I’m very happy to receive PRs but maybe this is not a good one unless you know `inotify` and `capnp` well. If not I should be able to deal with it sometime in the next few weeks

**Comment by Valicek1** [comment]
I am not familiar ethier of inotify or capnp, so it is not good idea to make this happen - this would only make new possible problems. I'll try to fix this with some nasty hack (ie. signal for config reload instead of restart of process - no loss of queued jobs - like it is done in other daemons). 
Thanks for your time and effort You put int this nice project.

**Comment by ohwgiles** [comment]
If you need a quick hack, you could just try adding a call to `loadConfiguration()` at the start of `Laminar::queueJob`. I did not try it, but it should cause the config to be refreshed whenever a new job is queued.

**Comment by ohwgiles** [comment]
@Valicek1 please try it out
