### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#39]
are you planning to extend the tool with some notifications? not only browser notifications, but support for external stuff?

**Comment by ohwgiles** [comment]
I'm not sure what you mean by "external stuff". In theory, notifications can be client-side or server-side. In the case of client-side, since the client is the browser there is not much more you can do than those popup notifications. On the server side you can in theory do anything, like send email, IRC or slack message. Is this what you are talking about? If so, laminar already "supports" them by script as described [here](https://github.com/ohwgiles/laminar#email-and-im-notifications). I realise that this isn't the most user-friendly, but it keeps laminar small and agnostic of other software. One way to make this easier would be to improve the documentation and add example scripts for common services. If you implement such a script, consider submitting a PR!

**Comment by palica** [comment]
ok, understand. will try.
