### ISSUE TITLE
LAMINAR_KEEP_WORKDIR has no effect

### ISSUE THREAD

**Issue by seifertm** [ohwgiles/laminar#4]
When I configure the environment variable LAMINAR_KEEP_WORKDIR, the directories of the individual job runs are not preserved.

Steps to reproduce
* Run as laminar user:
$ LAMINAR_BIND_HTTP=unix:/var/lib/laminar/laminard.sock LAMINAR_KEEP_WORKDIR=1 /usr/bin/laminard
* Trigger any job using laminarc

Expected results
The directory run/my-job/1/ is visible after the job crashed or finished.

Actual results
The directory run/my-job/1/ is temporarily visible. As soon as the job execution stops, the directory is removed.

BTW: I do like the project idea very much! Despite being a very young project, I chose to work with Laminar, because everything looks so tidy and polished :) Thanks for your efforts.

**Comment by ohwgiles** [comment]
Thanks for your detailed report and for trying out Laminar! I hope to keep it simple and shiny.

The idea is that the anything you need to keep you should move to `$ARCHIVE`, but I added this option as it could be useful to debug scripts. As it turns out, it has never worked, so while fixing it I've taken the opportunity to also give the config variable the more consistent name of `LAMINAR_KEEP_RUNDIR`. Commit 32426ee34 should resolve this issue
