### ISSUE TITLE
add new graphs to the home page?

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#45]
- It would be nice to spot which jobs suffered regression or recovered, but that might be too specific to my use-case. So like last failed job where previous job succeeded or vice versa show jobs that failed before but are ok after last run.
- pass rate of the package/job sorted
- how many jobs from a group failed%.
- show jobs that are taking longer/shorter then before (significantly)
- show average job run

**Comment by ohwgiles** [comment]
Most of these sound fine
- I agree that "recently regressed" and "recently recovered" lists would be nice.
- Maybe the 5 jobs with the highest failure/success ratio?
- By group you mean tag, right? This one is non-trivial because tags are not recorded in the database and thus cannot be queried against. I'd like to skip that for now.
- Build time spikes are a bit tricky to code for, since although you want to notice them, when a job correctly becomes longer you need to somehow "reset" your idea of "too long". The easiest way to do this is probably use a time period, like "top 5 largest changes in build time in the last week". Sounds ok?
- This one is probably most useful as a box-and-whisker chart. But how do you deal with the case of too many jobs? Just display the 5 with the highest mean? Is that even useful anymore?

**Comment by palica** [comment]
>     I agree that "recently regressed" and "recently recovered" lists would be nice.
- sound good
>     Maybe the 5 jobs with the highest failure/success ratio?
- could you make this configurable "5" "10" "custom" jobs ...
>     By group you mean tag, right? This one is non-trivial because tags are not recorded in the database and thus cannot be queried against. I'd like to skip that for now.
- ok to skip (group = tags)
>     Build time spikes are a bit tricky to code for, since although you want to notice them, when a job correctly becomes longer you need to somehow "reset" your idea of "too long". The easiest way to do this is probably use a time period, like "top 5 largest changes in build time in the last week". Sounds ok?
- I would probably get average from last x runs and compare to the recent run if more than threshold the display
>     This one is probably most useful as a box-and-whisker chart. But how do you deal with the case of too many jobs? Just display the 5 with the highest mean? Is that even useful anymore?
- this would be just for information and would show distribution of build/job run time. but understand that it is kind of hard to display for 20k jobs.
