### ISSUE TITLE
laminarc list jobs

### ISSUE THREAD

**Issue by Cynerd** [ohwgiles/laminar#67]
Would it be possible to have command to list running and queued jobs? Why I want that is to be able to limit amount of queued jobs. If there is already one queued then I don't want to queue another one. Secondary it would be good to have ability to quickly check that so there is no need for opening web browser.

It would be beneficial also if laminarc would be able to list all available jobs. If you implement that then I am willing to write you bash and zsh completion for laminarc to make it more usable.

It would be also good if `laminarc` could also terminate execution of job. To have that an ability to list running and queued jobs is essential.

**Comment by ohwgiles** [comment]
Nice idea. I think this is useful and also not too difficult to implement. Let's break it down:

- Listing running jobs with `laminarc show running`
- Listing queued jobs with `laminarc show queued`
- Listing available jobs with `laminarc show jobs` (maybe a better keyword?) - this one is also slightly more annoying to implement because laminard doesn't maintain a list of available jobs in memory, it just looks for a corresponding `.run` file when you try to queue a job. So the trivial implementation would cause a scan of the filesystem in `cfg/jobs` for every call. Not really a big deal all things considered.
- Abort a running job with `laminarc abort JOB NUMBER`

Sound right?

**Comment by Cynerd** [comment]
Yes that sounds all right. That is exactly what I wish for.

Small note to `laminarc show jobs`. I know that implementing that is not as easy as rest of them. But I can't implement it in completion it self because user running `laminarc` might not have access to laminar configuration and because of that this information has to  be received trough laminar it self. I don't think that scanning `cfg/jobs` is going to be a big burden. I expect it to be done pretty fast every time but it might be good idea to note this behavior in documentation so users won't place some additional content to that directory on top of essential files. I have all additional files in other directories in `cfg`.

**Comment by Cynerd** [comment]
Everything seems to work now. There is only this one problem where when I check for running jobs immediately after start it is reported twice. After a small moment (I have not measured it but it is faster than I am able to press up and enter so it might not be that big issue. Should I create separate issue for it?
