### ISSUE TITLE
Support jobs suspension

### ISSUE THREAD

**Issue by Cynerd** [ohwgiles/laminar#68]
I would like to see ability to suspend job execution by job it self. Meaning that process execution is suspended and its executor is freed for other job to run. Another process/job should then be able to request wake up of such suspended process. Laminar would wait for free original executor and process would be resumed.

Why I want that? I like that in Laminar I am able to use locks (flocks) to synchronize access to shared resources. I like this "use what is already there" philosophy. I am using that to have only one of job to do heavy lifting, preparing shared environment that all other jobs use later on. Problem is that that is pretty time consuming (which is also a reason why I am trying to do it only once in parallel). How it is done in other build systems is that job is marked as exclusive and only one execution is dispatched at a time. Laminar allows me to limit that to only really critical section. Problem is that this consumes executor slot during whole execution and can clearly bottleneck my real compilation server usage. This proposition should allow me to check if I can take lock and on failure suspend job it self (`kill -STOP $$`).

Example usage in job `compile`:
```
#!/bin/sh
while \! flock  --exclusive --wait 30 file.lock -c /bin/sh -s; do
    kill -STOP $$
done <<EOF
    . sdk-utils
    sdk_prepared || sdk_prepare
    sdk_copy
    laminarc resume compile
EOF
compile_software
```
Command `kill -STOP $$` causes root script to be stopped (also `-TSTP` might be used) that should be detected by laminar. Laminar should move this job from list of running to some new list of suspended job executions. On `laminarc resume compile` all suspended executions of job `compile` should be returned to queue, they should probably be queued even before any normally queued executions. When laminar wants to start such suspended job it should instead of forking new process just send `SIGCONT` to suspended pid.

**Comment by ohwgiles** [comment]
Hmm. This would probably not be too difficult to implement but I wonder if there is a simpler way to achieve what you want. What if, instead of triggering your job with `laminarc queue compile`, you instead did something like `laminarc queue sdk-prepare then=compile`. `sdk-prepare` would be a job that is limited to a single executor using tags. Its implementation could be something like
```
#!/bin/sh
sdk_prepared || sdk_prepare
sdk_copy
laminarc start $then
```
All your `$then` jobs would be tagged to run on a different set of executors. Because you call `laminarc start` instead of `queue`, the executor reserved for `sdk-queue` couldn't start the next `sdk-queue` until the real `compile` job has launched (and claimed an executor).

Does this make sense for your use case? One nice advantage of using tags over flocks is that the runtime stays meaningful.

**Comment by Cynerd** [comment]
Yes that is the way I have it setup at the moment. Problem is that what I want from executors and tags is to limit amount of paralel work. Meaning if I have 8 cores per compilation machine and I want to use 4 cores for every execution then I either have to dedicate 4 cores for single tag for SDK prepare or I have to over-commit one of machines to not only run two paralel compilation jobs but also SDK job (that is what I do at the moment). 4 dedicated cores for SDK prepare is just waste because this step has to be done in general at maximum once a day (detected by comparing local version to upstream reference before every build). On the other hand having over-committed machine causes SDK build to be slower than required.

I was thinking about it, how to solve that. What I really need is some programmable control of amount of executors. I have limited amount of resources and I do know how much one tag execution requires. I would need to be able to change amount of executors for every tag relative to already running jobs / occupied resources. That is not possible with current tag, executor design. So either I would have to propose some redesign of this part of Laminar or I have to go around and map executors directly to hardware resources. This introduces problem that I can't limit number of parallel jobs running at single moment. I can do that on my own with `flock` but that does not solves that because every executed job then stalls others if it waits for SDK.

Probably better solution would be to split idea of executors (tags) as both a way to limit amount of paralel jobs and hardware dedication to two separate components. Executors would be for hardware dedication and another way to limit number of paralel jobs would be introduced. That is really huge change and because of that I decided to propose something less invasive but usable for me too.

There might be some way how to do what I want with current nodes, tags implementation but I have not found one. Please suggest it to me if you see one.

**Comment by ohwgiles** [comment]
I see. I agree the current tags/executors system today (also discussed in #46) could be improved, so I'm totally open to a new design in this regard. I don't really want to tie the concept of executors too closely to hardware cores because there's no simple way of controlling the cores used by each job (scripts launch `make -j$foo` or similar).

A workaround you might consider that I've [suggested before](https://github.com/ohwgiles/laminar/issues/60#issuecomment-402964861), is to dynamically modify the `EXECUTORS=`  variable. Laminar will immediately recognise the change.

**Comment by ohwgiles** [comment]
I just noticed that I recently introduced a bug to `master` that broke nodes and tags. Should now be fixed in 7c600c6.

**Comment by ohwgiles** [comment]
Did you find an appropriate workaround for this? If not then we could open a discussion about how tags and executors should work in the future

**Comment by ohwgiles** [comment]
Closed as inactive. Feel free to reopen if you want to discuss further.
