### ISSUE TITLE
Started job is for brief moment after start reported twice

### ISSUE THREAD

**Issue by Cynerd** [ohwgiles/laminar#71]
When listing running jobs immediately after job is started then that specific job is reported twice.
```
$ laminarc start alpine-amd64 && laminarc show-running
alpine-amd64:125
alpine-amd64:125
```

* OS: Gentoo (portage from 14.10.2018)
* boost: 1.65.0

**Comment by ohwgiles** [comment]
I think what's happening here is two separate outputs. `laminarc start` will print the job name and number which was started. `laminarc queue` will print nothing because the job only gets assigned a number when it is popped off the queue for executing. If you don't need that output from laminarc you could try

`laminrc start alpine-amd64 >/dev/null && laminarc show-running`

**Comment by Cynerd** [comment]
Ups my fault. Of course queue does not print job name but start does.
```
$ laminarc start alpine-amd64 
alpine-amd64:167
```
Sorry there is no bug here.
