### ISSUE TITLE
`CMAKE_INSTALL_PREFIX` is not taken into account for some files

### ISSUE THREAD

**Issue by cipriancraciun** [ohwgiles/laminar#75]
It seems that although I set `-DCMAKE_INSTALL_PREFIX=/tmp/laminar`, the `make install` fails to obey it and tries to write to the "real" root:

````
# make sure we are in a clean state
rm -R -f /tmp/laminar
mkdir /tmp/laminar
git clean -f -d -x
````
````
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/laminar
make
make install
````
It fails with:
````
Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/laminar/usr/bin/laminard
-- Installing: /tmp/laminar/usr/bin/laminarc
CMake Error at cmake_install.cmake:81 (file):
  file cannot create directory: /lib/systemd/system.  Maybe need
  administrative privileges.
````

----

It seems that forcing `DESTDIR` and setting `CMAKE_INSTALL_PREFIX=/` does work:
````
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/
make
make install DESTDIR=/tmp/laminar
````

(Not setting `CMAKE_INSTALL_PREFIX` seems to result in some paths being installed as `/usr/share/usr/share`.)

**Comment by ohwgiles** [comment]
The problem is, the "prefix" is traditionally used whether to install the package under `/usr/local/` or under `/usr`. Unfortunately this breaks a bit when you need to install into `/etc` as laminar does. I'm not completely happy with this solution but at least now it's consistent. I recommend using `CMAKE_INSTALL_PREFIX=/` and passing `DESTDIR=` to `make install`.
