### ISSUE TITLE
Running `laminard` without installing it (with the "current folder" as its working directory)

### ISSUE THREAD

**Issue by cipriancraciun** [ohwgiles/laminar#76]
I understand (why/that) `laminar` takes the "classical" approach of UNIX "installation" by copying the files in `/etc`, `/bin`, `/var`, etc. and being started by a "proper" process supervisor (i.e. `systemd` / alternatives).

However, given today's "computing environment", and the fact that (mostly because of security concerns) some are reluctant to just `make install` (regardless of the configured prefix) --- as seen in issue #75 --- it would be lovely if `laminar` tools would work **out-of-the-box** without requiring a "root" install.

(In fact `laminar` does a perfect job of having almost no files, except the binaries, and being configured via environment variables.  +10 points for this!)  :)

Unfortunately, if I just run `./laminard` right out of the build folder, I get a "core dump":
````
./laminard 
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  kj/filesystem.c++:612: failed: directory does not exist; path = var/lib/laminar
Aborted (core dumped)
````

I would suggest using the current folder as the default `LAMINAR_HOME` if not overiden.

Unfortunately by just setting `LAMINAR_HOME=.` breaks as follows:
````
mkdir /tmp/laminar-run
/tmp/laminar-run
env LAMINAR_HOME=. ~/laminar/laminard
````
````
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  laminar.cpp:78: failed: expected home[0] == '/'
Aborted (core dumped)
````

However setting `LAMINAR_HOME=/proc/self/cwd` does seem to work.

(I know that one can just say `LAMINAR_HOME=/tmp/laminar-run` or even `LAMINAR_HOME="$( readlink -e . )"`, however these options seem contra-intuitive and serve no extra purpose.)

----

Moreover it seems that `laminard` ignores (without errors) any extra argument except `-v`.

**Comment by ohwgiles** [comment]
Typically during development I use `LAMINAR_HOME=$PWD ./laminard -v`.

I don't think that using the current folder as the default `LAMINAR_HOME` is a good idea. Configuration and artifacts will be loaded from/saved to this path. Suddenly when running it from one directory up e.g. `./build/laminard`, everything might appear "lost". I prefer it that the user is explicit and the default path is a sane installed path.

However, I agree that
1. Error message could be better
2. Relative paths in an explicitly-set `LAMINAR_HOME` could be supported
3. Unknown arguments to `laminard` should abort, or at least emit a warning

Since these are independent issues, please raise separate issues (or better still, PRs ;)
