### ISSUE TITLE
Reverse-proxy with custom base URL

### ISSUE THREAD

**Issue by bheisler** [ohwgiles/laminar#80]
I quite like Laminar, thanks for developing it. 

I've run into a small problem though. I'd like to run Laminar behind a reverse proxy, with the URL being `http://<HOST>/laminar`. However, all of the internal Javascript references and similar assume that Laminar is running at the root - eg. `http://<HOST>/js/vue.min.js`, which breaks because the reverse-proxy doesn't have a mapping for `/js`.

Is there a configuration option or something I can set to make this work?

**Comment by ohwgiles** [comment]
Thanks for using laminar. Unfortunately currently there isn't a way to achieve what you describe. Typically I think you would just run laminar at a different subdomain. However, I'm not opposed to making the non-root url work if it can be done efficiently.

I think changing the `<base href>` in `index.html` would be sufficient, but this file is static and gzipped at compile time. Perhaps it's possible to modify this attribute dynamically based on a header before the javascript is even fetched?

Ideas/contributions welcome ;)

**Comment by simevo** [comment]
this would be a very useful enhancement to laminar ! 

in html, `<base>` specifies the base URL for all **relative** URLs, so in `index.html` I set all URLs relative 

then if i delete `<base>`, static assets work both from http://example.com:8080 and from http://example.com/laminar, but:
- websockets does not work
- paths such as https://example.com/laminar/jobs/hello/1 break when you reload with F5 (it then looks in `/jobs/jobs/...` as opposed to when it hits that url from vue-router)

After any change to `index.html` of course I build and install:  `make && sudo systemctl stop laminar.service && sudo scp laminard /usr/bin/laminard && sudo systemctl start laminar.service`

for proxying I use nginx with:
```
location /laminar/ {

    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

with nginx we could easily set any header before proxying:
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header
...

**Comment by ohwgiles** [comment]
I experimented a bit with this. To fix the websockets it was necessary to set the [base property](https://router.vuejs.org/api/#base) of the `Vue-Router` instance.

The problem turns out to be how to set the `<base href>`. Modifying this dynamically with javascript `document.write` sort of works, but (at least in Chromium) fetches all the resources twice (first time with the old or default base href). Furthermore, it seems the only header you can read from javascript without making another request is cookies, which although could be used (maybe with immediate expiry), don't seem like the right way to deal with this. It's a pity `Content-Base` was deprecated, that would have been perfect for this case.

My best suggestion is: we fix the links and javascript so that `<base href>` works and leave it as the static default of `<base href="/">`. If you want to run laminar at a subdomain, you can match and replace the page content, with (for example) [sub_filter](http://nginx.org/en/docs/http/ngx_http_sub_module.html). How does that sound?

**Comment by simevo** [comment]
Hardwiring the `/laminar` path like in this proof of concept: https://github.com/simevo/laminar/commit/be270ffc3617ae6dd9e8e07744e2a9f1ee26abfc works for me; note that to fix `ws://` and console output logs I also have to modify the `app.js` file.

But all this seems too complex for  `sub_filter` ...

**Comment by ohwgiles** [comment]
Right, what I meant was doing essentially as you did, but also making the javascript retrieve the url from `<base href>` (`document.baseURI` might be enough), so that the only place `sub_filter` would have to modify is `<base href>`

**Comment by simevo** [comment]
what about adding a `LAMINAR_URL_PATH` option in `/etc/laminar.conf` ?

if this oprion is set, its value can be injected in `index.html` and `app.js` as soon as these are initialized in `src/resources.cpp`; no need to hack the JS or force the user to use nginx's `sub_filter`

**Comment by ohwgiles** [comment]
All the resources are gzipped at compile time, so can’t be dynamically modified without removing this very nice optimisation

**Comment by lboulard** [comment]
Hi,

A (long) time ago, I did write for personal usage a version of laminar 0.6 with support for sub URL and reverse proxy. I share in case it helps someone: <https://github.com/lboulard/laminar/tree/suburl>.
Feel free to cherry pick any change in this version that suit your needs.

It removes compression of html parts that need modifications for sub URL path, and, updates same parts on the fly on HTTP requests. Not efficient but it works.

Defines `LAMINAR_BASE_PATH` in `laminar.conf` to change base URL.
For example, with `LAMINAR_BASE_PATH=/laminar`,  use a `nginx` configuration like this one:

```conf
        location /laminar/ {
                proxy_pass              http://127.0.0.1:8080/;
                proxy_bind              127.0.0.1;
                proxy_http_version      1.1;

                proxy_set_header        Upgrade                 $http_upgrade;
                proxy_set_header        Connection              $connection_upgrade;
        }
```

I also share dpkg source packages of laminarc with patch for sub URL included for [debian/stretch](https://github.com/lboulard/laminar/tree/debian/stretch) and [ubuntu/xenial](https://github.com/lboulard/laminar/tree/ubuntu/xenial). Also fix build failure on 32bit architecture.

On RPI3, I use version for debian/stretch since and it works nicely.

Sorry to @ohwgiles for not sharing this before. But laminar code changed a lot since and I am sure that my changes are not in line with your expections for laminar project.

**Comment by simevo** [comment]
This looks like a good approach; in a typical reverse-proxy scenario, the laminar daemon and nginx run on the same machine, no need to gzip over that short path.
[Nginx can gzip the stuff on the fly](http://nginx.org/en/docs/http/ngx_http_gzip_module.html) before sending that over the internet.
This also makes it possible to alter dynamically a any time any html content generated by laminar.

**Comment by lboulard** [comment]
It was just a proof of concept. This is my first (and only) time doing javascript and modern JS framework.

Construction of root HTML page should be moved at initialization at start.
Better HTML index.html generation should be done by ressources class, not server class.

Then depending of scenario:
1. reverse proxy with caching and gzip:
    - remove gzip actions at compile time and store flat HTML
    - configure reverse proxy to handle compression
    - serve data in place of laminar, or, once laminar served it, let cache serve further requests
2. reverse proxy not doing caching or gzip
   - add dependency to laminar on gzip library
   - compress generated index.html and serve gzipped index.html on request

No opinion on which approach is worth trying. May be offer both at compile time but it add useless complexity.

**Comment by ohwgiles** [comment]
Thanks @lboulard for sharing - always nice to see what people are doing with laminar even if it's not always suitable to merge back.

@simevo Sure gzip is cheap to do on the fly, but it's the same operation for every request, which just feels wasteful even if it's insignificant. One of my goals with laminar is sticking to (at least practical) principles of minimalism and efficiency. This influenced my decision to put all the dynamic data in the websockets and keep all the html/js/images static. Unfortunately, the base url must be the only thing that doesn't seem to be feasible to push into websockets or http headers or anything else over which I still have dynamic "control".

I guess the long and short of it is, until a better solution presents itself, I don't want to remove the static gzipping. However I do intend to fix the URLs so that `<base href>` would be the only place you need to change it. Whether you want to do that in a fork or dynamically with `sub_filter` or something else is up to you. Also if there's anything else we can do to reduce the difficulty of running in this configuration _but without_ impacting the "normal" configuration, I'll happily consider merging it in.

**Comment by ohwgiles** [comment]
I just tried `sub_filter` and unfortunately it doesn't work on a gzipped backend. So I've reconsidered this and changed my mind about it, partially because I realised the substitution (and gzipping) can be done once at laminar startup and doesn't need to be done per request, so this can be just as runtime-efficient as the purely static case.
Hopefully I'll get a patch together in the next few days.

**Comment by simevo** [comment]
Hi, thanks for all the good work! With current master though the `LAMINAR_BASE_URL` does not work because many `:to` dynamic attributes point to absolute paths such as `/jobs...`

Please see this PR https://github.com/ohwgiles/laminar/pull/153

**Comment by ohwgiles** [comment]
@simevo thanks for finding and fixing that regression

**Comment by ohwgiles** [comment]
Yes, they should be there. I just checked and found a bug in the example though, [this line](https://github.com/ohwgiles/laminar/blob/399f07cf3ad884a86f47236bdef3f402dc8c9422/examples/nginx-ssl-reverse-proxy.conf#L41) should end with a slash, i.e. `proxy_pass http://127.0.0.1:8080/`, otherwise nginx will pass along your base url to laminar as part of the request url.

Does that solve your problem?

**Comment by psihozefir** [comment]
I have the following nginx configuration:
`location "/ci-cd" {
    limit_except GET { allow all; }
    proxy_pass http://127.0.0.1:8001/;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
}`
And nginx canot start because:
`2022/01/07 08:19:55 [emerg] 14812#14812: "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block`
If I remove the slash, it starts just fine.

**Comment by ohwgiles** [comment]
I tried the exact same config snippet and it worked for me. This is with nginx 1.20.2. Which version are you using?

**Comment by psihozefir** [comment]
I have version 1.14.2-2+deb10u4 running on Raspbian. It is updated to the latest available. I will try and see if there is a newer version somewhere or if I can use another OS that has the latest one.

**Comment by ohwgiles** [comment]
I tried version 1.14.2-2+deb10u4 in a docker image of Debian Buster. Works OK for me. I suggest dumping the full config with `nginx -T` and checking carefully, maybe there is an included configuration snippet which is breaking this setup.

**Comment by psihozefir** [comment]
Yes, this version seems to be working: nginx is starting fine. Perhaps the comment from 7 January was on an older version.

However, after setting `LAMINAR_BASE_URL=/ci-cd` and restarting `laminard` the root of the application is still `/`. The html is loading fine, but the resources do not: js, css, and icons.
I tried `proxy_pass http://127.0.0.1:8001/`, `proxy_pass http://127.0.0.1:8001` and `proxy_pass http://127.0.0.1:8001/ci-cd`.

**Comment by ohwgiles** [comment]
`LAMINAR_BASE_URL=/ci-cd/` and `location /ci-cd/` - note trailing slashes
