### ISSUE TITLE
Is there any (time) limit on workspace removal?

### ISSUE THREAD

**Issue by Cynerd** [ohwgiles/laminar#84]
I am encountering problems with Laminar that data are left in `run` directory. I have Laminar configured so it preserves only one workspace but for some jobs all directories are left. I notices that the problem is with workspaces that are just too big, around 14GB. In compare other workspaces are only around 3GB and they are successfully removed.

**Comment by ohwgiles** [comment]
This is the exact reason laminar deletes run dirs by default. If they are being left behind, it might be a bug. But the first thing to check is whether your job leaves behind files owned by a different user which the laminard process doesn’t have permission to delete.

**Comment by Cynerd** [comment]
One of my jobs is using something like unshare that have multiple users but that is not this job. I know about this possible issue and I clean that after my self. This is OpenWRT build and I am able to remove whole directory as a user laminard is running so that should not be a issue. I have other idea, there might be links that loop on each other. I am not sure if that is not a problem possibly but running `rm -rf` on that directory takes some time and in the end whole directory is removed without an error. But laminar fails to remove it.

**Comment by ohwgiles** [comment]
OK, so far it sounds like a bug. To your question, there is no time limit, and I think laminar should delete synchronously, so that it would block without accepting more jobs until the deletion finished. So there is anyway room for improvement here.

Without a way to exactly reproduce your issue, I can only suggest some debugging tips. Do you compile laminar? If so, I suggest adding a debug statement like `KJ_DBG("deleting rundir", d);` just before [this line](https://github.com/ohwgiles/laminar/blob/master/src/laminar.cpp#L863). Probably also worth checking the values of `oldestActive` and `numKeepRunDirs`.

If it helps, [this](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/kj/filesystem.h#L868) is the `kj` API  I use for the deletion.

**Comment by Cynerd** [comment]
Well it seems that it might have been fixed already. I am sorry about false alarm. I just updated from commit 77b8c8d6019f6bd58ef0e387c457bc358ca70a11 to master, added patch and it now successfully removes directories. Dropping patch changed nothing and it now still works.
